In [1]:
%load_ext autoreload
%autoreload 2

In [1]:
from prize_grid_env import PrizeGridEnv
import torch

In [3]:
env = PrizeGridEnv()
env.reset()

array([1, 0, 1, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 0, 2, 0, 0, 0, 0, 2,
       3, 0, 3, 3, 0, 0, 0, 0])

In [4]:
env.render()

[[ 1  0  1  0  1]
 [ 0  2  0  0  0]
 [ 0  0  1  2  1]
 [-1  2  0  0  0]
 [ 0  2  3  0  3]]


In [5]:
env._get_observation()

array([1, 0, 1, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 0, 2, 0, 0, 0, 0, 2,
       3, 0, 3, 3, 0, 0, 0, 0])

In [6]:
env.step(3)
env._get_observation()

array([1, 0, 1, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 0, 2, 0, 0, 0, 0, 2,
       3, 0, 3, 3, 1, 0, 1, 0])

In [7]:
env.prizes_threshold

array([2, 1, 1])

In [8]:
env.render()

[[ 1  0  1  0  1]
 [ 0  2  0  0  0]
 [ 0  0  1  2  1]
 [ 0 -1  0  0  0]
 [ 0  2  3  0  3]]


In [9]:
env.step(1)

(array([1, 0, 1, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 0, 2, 0, 0, 0, 0, 2,
        3, 0, 3, 4, 1, 0, 2, 0]),
 0,
 False,
 {})

In [10]:
env._get_observation()

array([1, 0, 1, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 0, 2, 0, 0, 0, 0, 2,
       3, 0, 3, 4, 1, 0, 2, 0])

In [13]:
len(env._get_observation())

30

In [2]:
from dqn import IncreasingConcaveNet

In [3]:
net = IncreasingConcaveNet([3, 1])
net.clamp_weights()

/Users/devarora/ml/submodular_nn/rl/dqn.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(
/Users/devarora/ml/submodular_nn/rl/dqn.py:31: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(


In [6]:
print(net(torch.tensor([0, 0, 0], dtype=torch.float)))
print(net(torch.tensor([0, 1, 0], dtype=torch.float)))
print(net(torch.tensor([1, 1, 0], dtype=torch.float)))
print(net(torch.tensor([1, 1, 1], dtype=torch.float)))



tensor([-3.1013e-07], grad_fn=<AddBackward0>)
tensor([1.0000], grad_fn=<AddBackward0>)
tensor([2.0000], grad_fn=<AddBackward0>)
tensor([3.0000], grad_fn=<AddBackward0>)


In [10]:
for i in range(20):
    for param in net.parameters():
        if param.requires_grad:
            noise = torch.randn_like(param) * 0.01
            param.data.add_(noise)
    net.clamp_weights()

    print(net(torch.tensor([0, 0, 0], dtype=torch.float)))
    print(net(torch.tensor([0, 1, 0], dtype=torch.float)))
    print(net(torch.tensor([1, 1, 0], dtype=torch.float)))
    print(net(torch.tensor([1, 1, 1], dtype=torch.float)))
    print("-" * 30)




tensor([0.0092], grad_fn=<AddBackward0>)
tensor([0.9992], grad_fn=<AddBackward0>)
tensor([2.0089], grad_fn=<AddBackward0>)
tensor([3.0052], grad_fn=<AddBackward0>)
------------------------------
tensor([0.0148], grad_fn=<AddBackward0>)
tensor([0.9825], grad_fn=<AddBackward0>)
tensor([1.9760], grad_fn=<AddBackward0>)
tensor([2.9758], grad_fn=<AddBackward0>)
------------------------------
tensor([0.0164], grad_fn=<AddBackward0>)
tensor([0.9795], grad_fn=<AddBackward0>)
tensor([1.9823], grad_fn=<AddBackward0>)
tensor([2.9810], grad_fn=<AddBackward0>)
------------------------------
tensor([0.0199], grad_fn=<AddBackward0>)
tensor([0.9812], grad_fn=<AddBackward0>)
tensor([1.9905], grad_fn=<AddBackward0>)
tensor([2.9894], grad_fn=<AddBackward0>)
------------------------------
tensor([0.0155], grad_fn=<AddBackward0>)
tensor([0.9946], grad_fn=<AddBackward0>)
tensor([1.9901], grad_fn=<AddBackward0>)
tensor([2.9937], grad_fn=<AddBackward0>)
------------------------------
tensor([0.0147], grad_fn=